### ISSUE TITLE
Add Basic Authentication

### ISSUE THREAD

**Issue by visola** [visola/go-http-cli#37]
Add an `auth` option in the yaml file so that people don't have to base64 encode user and password or even understand how that type of authorization works.

[This article](https://developer.mozilla.org/en-US/docs/Web/HTTP/Authentication) provides a good explanation of all types of authentication that exist. The two most common are `Basic` and `Bearer`. Implementing those two would be a great start.

The idea is that in the yaml file the user could add something like:
```yaml
auth:
  type: basic
  user: MyUsername
  password: myPassword
```

or 

```yaml
auth:
  type: bearer
  token: MyVeryLongTokenGoesHere
```
