### ISSUE TITLE
Add Request to Profile

### ISSUE THREAD

**Issue by visola** [visola/go-http-cli#42]
In a Profile, the user would be able to configure a request to be executed by passing an argument like `@login` to execute a common request.

The YAML file could be configured like (`profile.yml`):
```yaml
requests:
  - name: login
    url: /login
    headers:
       - Content-type: application-x-www-form-urlencoded
    method: POST
    body: username=MyUserName&password=MyPassword

  - name: create-employee
    url: /{orgId}/employees
    headers:
       - Content-type: application/json
    method: POST
```

Information passed in will be merged with the information provided. So for the second example, it would be possible to do the following:
```
$ http +profile @create-employee -d '{"name":"John Doe","birthdate":"1975-01-01"}'
```
